# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#Best config ever
title: HappyBlocks - Serveur minecraft
email: answer@happyblocks.info
description: Venez rejoindre HappyBlocks, une qualité exceptionnel de mini-jeux !
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://happyblocks.info" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: BlocksHappy
github_username: stoneset

# style settings
navigation_logo: assets/happyblocks.png # Le logo affiché dans la navigation
navigation:
    - text: Accueil
      link: /

    - text: Forum
      url: http://happyblocks.info/forum

    - text: Boutique
      url: http://happyblocks.info/shop

    - text: Stats
      url: http://happyblocks.info/stats

    - text: Vote
      link: /vote/

    - text: Autre
      dropdown:
          - text: E-Mail
            url: mailto:answer@happyblocks.info

          - text: Dons
            link: /dons/
#
#          - text: T-Shirt
#            link: /shop/

          - text: Discord
            url: http://discord.happyblocks.info/

          - text: Règles
            link: /Regles/

          - text: Crédits
            link: /Credits/

          - text: Statut
            link: /statut/
background:
    - image: /img/Backgrounds/01.jpg
      bright: true

    - image: /img/Backgrounds/02.jpg
      bright: true

    - image: /img/Backgrounds/03.jpg
      bright: true

    - image: /img/Backgrounds/04.jpg
      bright: true

background_speed: 10; # Vitesse du defilement du fond en seconde par image

# Build settings
markdown: kramdown
theme: minima
plugins:
    - jekyll-feed
exclude:
    - Gemfile
    - Gemfile.lock
safe: true
include: 
    - _redirects
